"""add meeting link to class sessions

Revision ID: 5b1ff5e5abae
Revises: 164ac942e343
Create Date: 2026-08-31 12:23:44.685824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5b1ff5e5abae'
down_revision: Union[str, Sequence[str], None] = '164ac942e343'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('class_sessions', sa.Column('meeting_link', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('class_sessions', 'meeting_link')
    # ### end Alembic commands ###
