"""add meeting link to class sessions

Revision ID: 5b1ff5e5abae
Revises: 164ac942e343
Create Date: 2026-08-31 12:23:44.685824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5b1ff5e5abae'
down_revision: Union[str, Sequence[str], None] = '164ac942e343'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('flyway_schema_history_s_idx'), table_name='flyway_schema_history')
    op.drop_table('flyway_schema_history')
    op.add_column('class_sessions', sa.Column('meeting_link', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('class_sessions', 'meeting_link')
    op.create_table('flyway_schema_history',
    sa.Column('installed_rank', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('version', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('script', sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
    sa.Column('checksum', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('installed_by', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('installed_on', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('execution_time', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('success', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('installed_rank', name=op.f('flyway_schema_history_pk'))
    )
    op.create_index(op.f('flyway_schema_history_s_idx'), 'flyway_schema_history', ['success'], unique=False)
    # ### end Alembic commands ###
