package com.Project.LearningManagementSystem;

import org.junit.jupiter.api.Test;
import org.springframework.security.crypto.argon2.Argon2PasswordEncoder;
import static org.junit.jupiter.api.Assertions.assertTrue;

public class PasswordMatchTest {

    @Test
    void testPasswordCrossCompatibility() {
        Argon2PasswordEncoder encoder = Argon2PasswordEncoder.defaultsForSpringSecurity_v5_8();
        // Hash generated by Python Argon2id
        String pythonHash = "$argon2id$v=19$m=65536,t=3,p=4$ESPuYZ/hO+WX1one6+7Zag$QN/l4XDvzRHlsDU677ceZ7Qs5StFqMp65H+RCEdGkvM";
        boolean matches = encoder.matches("admin123", pythonHash);
        System.out.println("Java verified Python hash: " + matches);
        assertTrue(matches);

        String javaHash = encoder.encode("admin123");
        System.out.println("Java generated hash: " + javaHash);
        assertTrue(encoder.matches("admin123", javaHash));
    }
}
